### ISSUE TITLE
syntax error, unexpected

### ISSUE THREAD

**Issue by FlashPapa** [luanfreitasdev/livewire-datatable#2]
Hi,
I've got this problem ->

_vendor/luanfreitasdev/livewire-datatable/src/DataTableComponent.php:192_

![🧨_syntax_error__unexpected______expecting_____or__{___View___var_www_html_larawind_resources_views_contacts_index_blade_php_](https://user-images.githubusercontent.com/2919658/113327530-5e465600-931b-11eb-8411-b7268bf43100.png)

My composer require :

<img width="439" alt="larawind_–_composer_json" src="https://user-images.githubusercontent.com/2919658/113327116-d82a0f80-931a-11eb-99e8-d8d909ece266.png">

Any ideas ?

Thanks

**Comment by luanfreitasdev** [comment]
Hello @FlashPapa , thanks for report this bug, a php8 version code was probably pushed, this has been fixed. 
Please upgrade to version v1.0.6

`composer update luanfreitasdev/livewire-datatable`

Wait for our next update with many other features, including advanced filter and improved theme
